stages:
  - deploy

deploy:
  stage: deploy
  image: node
  script:
    - npm install -g heroku
    - git remote rm heroku && git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/react-nextify.git
    - git push -f heroku HEAD:master
  only:
    - merge_requests
